[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bnn_package"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["."] 
include = ["bnn_package*"] 