[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bnn_package"
version = "0.1.0"
dependencies = ["numpy", 
                "scipy", 
                "numba", 
                "tqdm", 
                "matplotlib", 
                "entropy"]

[tool.setuptools.packages.find]
where = ["."] 
include = ["bnn_package*"] 