mode: run_order_parameter
output_file: results_paper_config_for_CS_Diff.csv
parallel: true
cores_ratio: 0.8
output_folder: Data_output
seed: 1234567890
quick_analyze_graph: false
number_of_nodes: 1000
square_for_graph: [10.0, 10.0]
diffusive_operator: Diffusive
std: 0.3
mean_poisson: 0.7
total_time: 100000
transitory_time: 0
dt: 0.01
alpha: 0.2
a: 3.0
k: 0.25
vrp: 1.5
fhn_eps: 0.08
epsilon: [0.0, 0.3888888888888889, 0.7777777777777778, 1.1666666666666667, 1.5555555555555556,
  1.9444444444444444, 2.3333333333333335, 2.7222222222222223, 3.111111111111111, 3.5]
metrics: [COH, OSC, FMSD]
cr: [0.0, 0.2222222222222222, 0.4444444444444444, 0.6666666666666666, 0.8888888888888888,
  1.1111111111111112, 1.3333333333333333, 1.5555555555555554, 1.7777777777777777,
  2.0]
threshold: 0.7
existing_graph_path: Data_output/graphs_registry/graph_N1000_std0.3_0219961d.npz
