mode: run_order_parameter
output_file: results_Phase_Diagram.csv
parallel: true
cores_ratio: 0.8
output_folder: Data_output
seed: 1234567890
quick_analyze_graph: false
number_of_nodes: 1000
square_for_graph: [10.0, 10.0]
diffusive_operator: Diffusive
std: 0.3
mean_poisson: 0.7
total_time: 100000
transitory_time: 0
dt: 0.01
alpha: 0.2
a: 3.0
k: 0.25
vrp: 1.5
fhn_eps: 0.08
epsilon: [0.0, 0.10294117647058823, 0.20588235294117646, 0.3088235294117647, 0.4117647058823529,
  0.5147058823529411, 0.6176470588235294, 0.7205882352941176, 0.8235294117647058,
  0.926470588235294, 1.0294117647058822, 1.1323529411764706, 1.2352941176470589, 1.338235294117647,
  1.4411764705882353, 1.5441176470588234, 1.6470588235294117, 1.75, 1.852941176470588,
  1.9558823529411764, 2.0588235294117645, 2.161764705882353, 2.264705882352941, 2.3676470588235294,
  2.4705882352941178, 2.5735294117647056, 2.676470588235294, 2.7794117647058822, 2.8823529411764706,
  2.985294117647059, 3.0882352941176467, 3.191176470588235, 3.2941176470588234, 3.3970588235294117,
  3.5]
metrics: [COH, OSC, FMSD]
cr: [0.0, 0.058823529411764705, 0.11764705882352941, 0.1764705882352941, 0.23529411764705882,
  0.29411764705882354, 0.3529411764705882, 0.4117647058823529, 0.47058823529411764,
  0.5294117647058824, 0.5882352941176471, 0.6470588235294118, 0.7058823529411764,
  0.7647058823529411, 0.8235294117647058, 0.8823529411764706, 0.9411764705882353,
  1.0, 1.0588235294117647, 1.1176470588235294, 1.1764705882352942, 1.2352941176470589,
  1.2941176470588236, 1.3529411764705883, 1.4117647058823528, 1.4705882352941175,
  1.5294117647058822, 1.588235294117647, 1.6470588235294117, 1.7058823529411764, 1.7647058823529411,
  1.8235294117647058, 1.8823529411764706, 1.9411764705882353, 2.0]
threshold: 0.7
existing_graph_path: Data_output/graphs_registry/graph_N1000_std0.3_f0db19e8.npz
